/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface MultipleValues {
      /**
       * Button's class
       */
      'buttonClass': string;
      /**
       * If true, the inputs can edit
       */
      'canEdit': boolean;
      /**
       * Class of button's container
       */
      'containerButtonsClass': string;
      /**
       * Class of container of all inputs
       */
      'containerClass': string;
      /**
       * Class of input's container
       */
      'containerInputClass': string;
      /**
       * The name of the label of inputs
       */
      'label': string;
      /**
       * The class of the label
       */
      'labelClass': string;
      /**
       * Class of row (one row = one element of the data object = one group of inputs)
       */
      'rowClass': string;
      /**
       * The value of the component (multiple-values) 
       */
      'value': Array<any>;
    }
  }

  interface HTMLMultipleValuesElement extends StencilComponents.MultipleValues, HTMLStencilElement {}

  var HTMLMultipleValuesElement: {
    prototype: HTMLMultipleValuesElement;
    new (): HTMLMultipleValuesElement;
  };
  interface HTMLElementTagNameMap {
    'multiple-values': HTMLMultipleValuesElement;
  }
  interface ElementTagNameMap {
    'multiple-values': HTMLMultipleValuesElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'multiple-values': JSXElements.MultipleValuesAttributes;
    }
  }
  namespace JSXElements {
    export interface MultipleValuesAttributes extends HTMLAttributes {
      /**
       * Button's class
       */
      'buttonClass'?: string;
      /**
       * If true, the inputs can edit
       */
      'canEdit'?: boolean;
      /**
       * Class of button's container
       */
      'containerButtonsClass'?: string;
      /**
       * Class of container of all inputs
       */
      'containerClass'?: string;
      /**
       * Class of input's container
       */
      'containerInputClass'?: string;
      /**
       * The name of the label of inputs
       */
      'label'?: string;
      /**
       * The class of the label
       */
      'labelClass'?: string;
      /**
       * Emitted when the value change
       */
      'onValuechange'?: (event: CustomEvent) => void;
      /**
       * Class of row (one row = one element of the data object = one group of inputs)
       */
      'rowClass'?: string;
      /**
       * The value of the component (multiple-values) 
       */
      'value'?: Array<any>;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;